### ISSUE TITLE
add wchar support

### ISSUE THREAD

**Issue by stsp** [stsp/dj64dev#11]
In order to compile modern ncurses,
we need wchar support.

**Comment by stsp** [comment]
I ported the wchar support from
64tass project, but it is under GPLv2+.

@irmen would it be possible to permit
me to distribute your wchar.c under LGPLv3+
or LGPLv2.1+? Otherwise it may be
problematic to include into djgpp libc
or its forks (like this one).

**Comment by irmen** [comment]
64tass is not my project, it's a clone of the official repository on SourceForge https://sourceforge.net/projects/tass64/  by Soci.

You should ask the original author there. I can't make this decision.

**Comment by stsp** [comment]
Ok, thank you for info.
I filled the ticket there:
https://sourceforge.net/p/tass64/feature-requests/25/

**Comment by stsp** [comment]
Got the LGPLv3+ permission from
Soci by the above URL.

**Comment by stsp** [comment]
@jwt27 now that dj64dev have some
unicode support (enough to build ncurses
with wchar support), maybe you are
interested in porting this to djgpp as well.

**Comment by jwt27** [comment]
Interesting, thanks for the ping.  But would you believe... there was already a wchar patch for djgpp, submitted way back in 1998 :)

As I understand it was decided to look at this for 2.06, but that didn't happen yet.  Who knows if it ever will.

https://www.delorie.com/djgpp/mail-archives/browse.cgi?p=djgpp/2017/07/22/12:16:31

The link mentioned here is down, and archive.org doesn't have it either.  I thought I had it saved somewhere, but can't seem to find it again. Ping @apavenis ?
