### ISSUE TITLE
Building on gentoo.  No djlink, dj64-gcc, etc.

### ISSUE THREAD

**Issue by sikofitt** [stsp/dj64dev#20]
Hi, i'm trying to build this so I can build comcom64.  I've successfully built dosemu2.  But it doesn't seem to be creating or installing any binaries.  When I run make uninstall to tries to remove binaries from /usr/local/bin though.

Thanks.

**Comment by stsp** [comment]
You need to build smallerc, djstub
and thunk_gen packages first.

**Comment by stsp** [comment]
Also not sure why you mentioned `dj64-gcc`.
This was the script that is long ago removed.
If  you still need it, you are not up to date.
